apiVersion: v1
kind: Service
metadata:
  name: rewear-backend-service
  labels:
    app: rewear-backend   # ← IMPORTANT (used by ServiceMonitor)
spec:
  type: NodePort
  selector:
    app: rewear-backend
  ports:
    - name: http          # ✅ MUST ADD THIS
      port: 80
      targetPort: 5000
      nodePort: 30007